//
//  HappyActionIcons.h
//  hAppy
//
//  Created by Dominik Hauser on 02.10.14.
//  Copyright (c) 2014 Dominik Hauser. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface HappyActionIcons : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* replyTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* repostTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* favTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* conversationTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* favedTargets;

// Generated Images
+ (UIImage*)imageOfReplyWithSize: (CGSize)size;
+ (UIImage*)imageOfRepostWithSize: (CGSize)size;
+ (UIImage*)imageOfFavWithSize: (CGSize)size;
+ (UIImage*)imageOfConversationWithSize: (CGSize)size;
+ (UIImage*)imageOfFavedWithSize: (CGSize)size;

@end
